version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  allow:
  - dependency-name: Bullseye
  - dependency-name: Glob
  - dependency-name: SimpleExec
  - dependency-name: XmlDocMarkdown.Core
