version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: /FLJCPNtLDyXDbw62wnY4tBc3kRJMPNbttutkzVhCdUDEmg9pjEBGZnBVpBTemKK
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
build_script:
- cmd: .\build.cmd package
- sh: ./build.sh package
test: off
for:
  -
    branches:
      only:
        - master
    build_script:
    - cmd: .\build.cmd publish --trigger=publish-all "--build-number=%APPVEYOR_BUILD_NUMBER%"
    - sh: ./build.sh package
