version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: /FLJCPNtLDyXDbw62wnY4tBc3kRJMPNbttutkzVhCdUDEmg9pjEBGZnBVpBTemKK
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
build_script:
- cmd: if %APPVEYOR_REPO_BRANCH% neq master .\build.cmd package
- cmd: if %APPVEYOR_REPO_BRANCH% equ master if defined APPVEYOR_PULL_REQUEST_NUMBER .\build.cmd package
- cmd: if %APPVEYOR_REPO_BRANCH% equ master if not defined APPVEYOR_PULL_REQUEST_NUMBER .\build.cmd publish --trigger=publish-all --build-number=%APPVEYOR_BUILD_NUMBER%
- sh: ./build.sh package
test: off
