version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: /FLJCPNtLDyXDbw62wnY4tBc3kRJMPNbttutkzVhCdUDEmg9pjEBGZnBVpBTemKK
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
build_script:
- cmd: .\build.cmd package
- sh: ./build.sh package
test: off
deploy:
  - provider: Environment
    name: production
    on:
      branch: master
deploy_script:
- cmd: .\build.cmd publish --no-test --trigger=publish-all "--build-number=%APPVEYOR_BUILD_NUMBER%"
- sh: echo Deployed from Windows build.
